---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{PROJECT_NAME}}
  annotations:
    kubernetes.io/ingress.class: 'nginx'
spec:
  rules:
  - host: {{PROJECT_NAME}}.afharvey.com
    http:
      paths:
      - path: /
        backend:
          serviceName: {{PROJECT_NAME}}-svc
          servicePort: 80
  - host: hello.afharvey.com
    http:
      paths:
      - path: /
        backend:
          serviceName: {{PROJECT_NAME}}-svc
          servicePort: 80