---
apiVersion: v1
kind: Service
metadata:
  name: {{PROJECT_NAME}}
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
  selector:
    app: {{PROJECT_NAME}}
