---
apiVersion: v1
kind: Service
metadata:
  name: {{PROJECT_NAME}}
  labels:
    app: {{PROJECT_NAME}}
    name: {{PROJECT_NAME}}
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer # ClusterIP
  selector:
    app: {{PROJECT_NAME}}